language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: jDOVHvflPKQzQhp/rcq0y/mU0EI9lXP0SwTLlUHjwQg/x1KrTZyJpHRiZEgHbGwlASLYiwRzRJUpFbr2CbotZxlRhW6c+uWOj4GXCu5rNQDh5Jldypp1vqIhtT/Cfeqou/uWt3ecZMJRX4C1vGIwqGd1H0B6jePjWrX66obYakTX13KtA0Qr8zrxTWT+Y8846zLk9rlabw3lpWbuwzDgxa0zZVbeupDTE2wzRACUyuQFVDJaOCVJo+xOpnkywJsgt9MjzK8LR3rOcDygF7ph51GIrERRRvDNmVMWllweC//8TXVaVTyfPIVZ63UAbUTQZWbJV1hcRL8f1vVpgNmbIA9NvrDO98BFGCIgxZPp3DJX+e915x6RRmv5clxAO9fW64qjfmi6RkQCkukr4A3GQz7NQ6U+w/51tSFlD7DL4n1gQjhUDG/SDul1jXONjVJaEEf9jC7pmoxo1wXoeznMgEYAU7Jm8+SKk5PksQvLaq899rg87Tq7kU/YOhAfYyo6m1YGHHMdJMejR6HpGD00pZKyC5eZ4MG9wxSMNlblgUYp8bpVoTugcQPzFcFtSRMuqxCjrl1aI2lYFh+m5wcBMRBKZfDJ+AUBWpROSiud2MVU8BEdE3aLG6hUZj4NhHh3zpZ/XuB99g7iiDF8CTvW+Z2w9CLzKKQcJZd1Z622AvE=
